import { Candidate, Drive, Assessment, AICandidate, AnalyticsData } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@gmail.com',
    phone: '+91 9876543210',
    university: 'SRM University',
    degree: 'B.Tech Computer Science',
    yearsOfExperience: 0,
    skills: ['JavaScript', 'React', 'Node.js'],
    resumeUrl: '/resumes/rahul-sharma.pdf',
    appliedDate: '2023-04-15',
    status: 'assessment',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '2',
    name: 'Priya Patel',
    email: 'priya.patel@gmail.com',
    phone: '+91 9876543211',
    university: 'KCG College of Technology',
    degree: 'B.Tech Information Technology',
    yearsOfExperience: 0,
    skills: ['Java', 'Spring Boot', 'MySQL'],
    resumeUrl: '/resumes/priya-patel.pdf',
    appliedDate: '2023-04-16',
    status: 'screening',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '3',
    name: 'Arun Kumar',
    email: 'arun.kumar@gmail.com',
    phone: '+91 9876543212',
    university: 'Anna University',
    degree: 'M.Tech Computer Science',
    yearsOfExperience: 1,
    skills: ['Python', 'Django', 'PostgreSQL'],
    resumeUrl: '/resumes/arun-kumar.pdf',
    appliedDate: '2023-04-17',
    status: 'interview',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '4',
    name: 'Deepika Reddy',
    email: 'deepika.reddy@gmail.com',
    phone: '+91 9876543213',
    university: 'VIT Vellore',
    degree: 'B.Tech Electronics',
    yearsOfExperience: 0,
    skills: ['C++', 'Embedded Systems', 'IoT'],
    resumeUrl: '/resumes/deepika-reddy.pdf',
    appliedDate: '2023-04-18',
    status: 'applied',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram.singh@gmail.com',
    phone: '+91 9876543214',
    university: 'IIT Madras',
    degree: 'B.Tech Computer Science',
    yearsOfExperience: 0,
    skills: ['AI/ML', 'TensorFlow', 'Python'],
    resumeUrl: '/resumes/vikram-singh.pdf',
    appliedDate: '2023-04-19',
    status: 'offer',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '6',
    name: 'Ananya Desai',
    email: 'ananya.desai@gmail.com',
    phone: '+91 9876543215',
    university: 'BITS Pilani',
    degree: 'M.Tech Data Science',
    yearsOfExperience: 1,
    skills: ['Data Science', 'R', 'Tableau'],
    resumeUrl: '/resumes/ananya-desai.pdf',
    appliedDate: '2023-04-20',
    status: 'hired',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];

export const mockDrives: Drive[] = [
  {
    id: '1',
    title: 'Software Engineer Campus Drive',
    company: 'Zoho Corporation',
    location: 'Chennai, Tamil Nadu',
    description: 'Looking for fresh graduates with strong programming skills to join our development team.',
    positions: 25,
    startDate: '2023-05-10',
    endDate: '2023-06-10',
    status: 'active',
    candidatesApplied: 150,
    candidatesShortlisted: 45,
    rounds: [
      {
        id: '1-1',
        name: 'Resume Screening',
        type: 'screening',
        date: '2023-05-10',
        duration: 7,
        status: 'completed',
        candidatesCount: 150,
      },
      {
        id: '1-2',
        name: 'Online Assessment',
        type: 'assessment',
        date: '2023-05-20',
        duration: 2,
        status: 'ongoing',
        candidatesCount: 75,
      },
      {
        id: '1-3',
        name: 'Technical Interview',
        type: 'interview',
        date: '2023-05-30',
        duration: 5,
        status: 'pending',
        candidatesCount: 0,
      },
      {
        id: '1-4',
        name: 'HR Interview',
        type: 'hr',
        date: '2023-06-05',
        duration: 3,
        status: 'pending',
        candidatesCount: 0,
      },
    ],
    logo: 'https://i.imgur.com/iW1QN5j.png',
  },
  {
    id: '2',
    title: 'Product Management Trainee',
    company: 'Tata Consultancy Services',
    location: 'Bangalore, Karnataka',
    description: 'Seeking fresh graduates with excellent analytical and communication skills.',
    positions: 10,
    startDate: '2023-05-15',
    endDate: '2023-06-15',
    status: 'active',
    candidatesApplied: 85,
    candidatesShortlisted: 30,
    rounds: [
      {
        id: '2-1',
        name: 'Resume Screening',
        type: 'screening',
        date: '2023-05-15',
        duration: 7,
        status: 'completed',
        candidatesCount: 85,
      },
      {
        id: '2-2',
        name: 'Case Study Assessment',
        type: 'assessment',
        date: '2023-05-25',
        duration: 3,
        status: 'pending',
        candidatesCount: 0,
      },
      {
        id: '2-3',
        name: 'Group Discussion',
        type: 'interview',
        date: '2023-06-01',
        duration: 2,
        status: 'pending',
        candidatesCount: 0,
      },
      {
        id: '2-4',
        name: 'Final Interview',
        type: 'hr',
        date: '2023-06-10',
        duration: 3,
        status: 'pending',
        candidatesCount: 0,
      },
    ],
    logo: 'https://i.imgur.com/VPgogGp.png',
  },
  {
    id: '3',
    title: 'Game Developer Internship',
    company: 'Assetto Corsa India',
    location: 'Hyderabad, Telangana',
    description: 'Looking for passionate game developers with knowledge of Unity or Unreal Engine.',
    positions: 5,
    startDate: '2023-06-01',
    endDate: '2023-06-30',
    status: 'draft',
    candidatesApplied: 0,
    candidatesShortlisted: 0,
    rounds: [
      {
        id: '3-1',
        name: 'Portfolio Review',
        type: 'screening',
        date: '2023-06-01',
        duration: 5,
        status: 'pending',
        candidatesCount: 0,
      },
      {
        id: '3-2',
        name: 'Coding Challenge',
        type: 'assessment',
        date: '2023-06-10',
        duration: 2,
        status: 'pending',
        candidatesCount: 0,
      },
      {
        id: '3-3',
        name: 'Technical Interview',
        type: 'interview',
        date: '2023-06-20',
        duration: 3,
        status: 'pending',
        candidatesCount: 0,
      },
    ],
    logo: 'https://i.imgur.com/UT42zjB.png',
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: '1',
    title: 'Java Programming Fundamentals',
    description: 'Basic Java programming concepts and problem-solving skills assessment.',
    duration: 60,
    totalQuestions: 20,
    type: 'mcq',
    difficulty: 'easy',
    topics: ['Java Syntax', 'OOP Concepts', 'Data Structures'],
    createdAt: '2023-01-15',
  },
  {
    id: '2',
    title: 'Frontend Developer Challenge',
    description: 'Assessment for React.js knowledge and frontend skills.',
    duration: 90,
    totalQuestions: 5,
    type: 'coding',
    difficulty: 'medium',
    topics: ['React', 'JavaScript', 'CSS', 'HTML'],
    createdAt: '2023-02-20',
  },
  {
    id: '3',
    title: 'Database Management Systems',
    description: 'SQL queries and database design concepts assessment.',
    duration: 45,
    totalQuestions: 15,
    type: 'mcq',
    difficulty: 'medium',
    topics: ['SQL', 'Database Design', 'Normalization'],
    createdAt: '2023-03-10',
  },
  {
    id: '4',
    title: 'Data Structures and Algorithms',
    description: 'Problem-solving using efficient data structures and algorithms.',
    duration: 120,
    totalQuestions: 3,
    type: 'coding',
    difficulty: 'hard',
    topics: ['Arrays', 'Linked Lists', 'Trees', 'Dynamic Programming'],
    createdAt: '2023-04-05',
  },
];

export const mockAICandidates: AICandidate[] = [
  {
    id: '1',
    name: 'Sanjeev Kapoor',
    currentCompany: 'TechSolutions India',
    currentRole: 'Senior Software Engineer',
    experience: 5,
    skills: ['Java', 'Spring Boot', 'Microservices', 'AWS'],
    education: 'M.Tech from IIT Delhi',
    matchScore: 95,
    profileUrl: 'https://linkedin.com/in/sanjeev-kapoor',
    avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '2',
    name: 'Anjali Menon',
    currentCompany: 'GlobalTech',
    currentRole: 'Lead Developer',
    experience: 7,
    skills: ['Python', 'Django', 'Machine Learning', 'SQL'],
    education: 'B.Tech from NIT Trichy',
    matchScore: 88,
    profileUrl: 'https://linkedin.com/in/anjali-menon',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '3',
    name: 'Rohan Desai',
    currentCompany: 'Startup Innovators',
    currentRole: 'Full Stack Developer',
    experience: 4,
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    education: 'B.E. from BITS Pilani',
    matchScore: 82,
    profileUrl: 'https://linkedin.com/in/rohan-desai',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '4',
    name: 'Priya Gupta',
    currentCompany: 'Data Analytics Pro',
    currentRole: 'Data Scientist',
    experience: 3,
    skills: ['Python', 'R', 'TensorFlow', 'Data Visualization'],
    education: 'M.S. in Data Science from IISc Bangalore',
    matchScore: 79,
    profileUrl: 'https://linkedin.com/in/priya-gupta',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '5',
    name: 'Karthik Rajan',
    currentCompany: 'Cloud Solutions Ltd',
    currentRole: 'DevOps Engineer',
    experience: 6,
    skills: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform'],
    education: 'B.Tech from Anna University',
    matchScore: 75,
    profileUrl: 'https://linkedin.com/in/karthik-rajan',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];

export const mockAnalytics: AnalyticsData = {
  applicationsCount: 563,
  interviewsScheduled: 128,
  offersExtended: 42,
  acceptanceRate: 85,
  averageTimeToHire: 28,
  departmentBreakdown: [
    { name: 'Computer Science', value: 40 },
    { name: 'Electronics', value: 25 },
    { name: 'Mechanical', value: 15 },
    { name: 'Civil', value: 10 },
    { name: 'Electrical', value: 10 },
  ],
  placementByDepartment: [
    { name: 'Computer Science', placed: 35, notPlaced: 5 },
    { name: 'Electronics', placed: 20, notPlaced: 5 },
    { name: 'Mechanical', placed: 10, notPlaced: 5 },
    { name: 'Civil', placed: 7, notPlaced: 3 },
    { name: 'Electrical', placed: 8, notPlaced: 2 },
  ],
  skillDistribution: [
    { name: 'JavaScript', value: 28 },
    { name: 'Java', value: 22 },
    { name: 'Python', value: 18 },
    { name: 'C++', value: 12 },
    { name: 'SQL', value: 10 },
    { name: 'Others', value: 10 },
  ],
  assessmentCompletion: [
    { name: 'Completed', value: 65 },
    { name: 'Partially Completed', value: 15 },
    { name: 'Not Started', value: 10 },
    { name: 'Timed Out', value: 10 },
  ],
    monthlyHires: [
    { name: 'Jan', value: 4 },
    { name: 'Feb', value: 6 },
    { name: 'Mar', value: 8 },
    { name: 'Apr', value: 10 },
    { name: 'May', value: 12 },
    { name: 'Jun', value: 8 },
    { name: 'Jul', value: 6 },
    { name: 'Aug', value: 9 },
    { name: 'Sep', value: 11 },
    { name: 'Oct', value: 7 },
    { name: 'Nov', value: 5 },
    { name: 'Dec', value: 3 },
  ],
};
